import {
  faArrowDown, faArrowLeft, faAsterisk, faBan, faBars, faBell, faBolt, faBoltLightning, faBook, faCalendarAlt, faChair,
  faCheck, faCircle, faCircleCheck, faCircleHalfStroke, faCircleInfo, faClock, faCloud, faCogs, faComments,
  faCommentsDollar, faCreditCard, faCube, faDatabase, faEnvelope, faEnvelopeCircleCheck, faEye, faFileImport,
  faFireBurner, faFlag, faFloppyDisk, faHandshakeSimple, faHeart, faHome, faLink, faList, faLocationDot, faLock,
  faLockOpen, faMapLocationDot, faMinus, faMoneyBill, faMugHot, faNoteSticky, faPager, faPencilAlt, faPeopleArrows,
  faPerson, faPhone, faPiggyBank, faPlus, faRepeat, faRoad, faRotate, faSave, faSearch, faSheetPlastic, faShower,
  faSignature, faSignInAlt, faSignOutAlt, faSlash, faSort, faSortDown, faSortUp, faSpinner, faStar, faSync,
  faTachometerAlt, faTag, faTasks, faThList, faTimes, faTrashAlt, faTrashCan, faTriangleExclamation, faUmbrella, faUser,
  faUserPlus, faUsers, faUsersCog, faUserSlash, faWandMagicSparkles, faWrench,
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeIcons = [
  faArrowLeft,
  faArrowDown,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBolt,
  faBook,
  faCalendarAlt,
  faChair,
  faCheck,
  faCircle,
  faCircleCheck,
  faCircleInfo,
  faCircleHalfStroke,
  faClock,
  faCloud,
  faCogs,
  faCommentsDollar,
  faComments,
  faCreditCard,
  faCube,
  faDatabase,
  faEnvelope,
  faEnvelopeCircleCheck,
  faEye,
  faFileImport,
  faFireBurner,
  faFlag,
  faFloppyDisk,
  faHandshakeSimple,
  faHeart,
  faHome,
  faLink,
  faList,
  faLocationDot,
  faLock,
  faLockOpen,
  faMapLocationDot,
  faMinus,
  faMoneyBill,
  faMugHot,
  faNoteSticky,
  faPager,
  faPencilAlt,
  faPeopleArrows,
  faPerson,
  faPhone,
  faPiggyBank,
  faPlus,
  faRepeat,
  faRoad,
  faRotate,
  faSave,
  faSearch,
  faSheetPlastic,
  faShower,
  faSignature,
  faSignOutAlt,
  faSignInAlt,
  faSlash,
  faSort,
  faSortDown,
  faSortUp,
  faSpinner,
  faStar,
  faSync,
  faTachometerAlt,
  faTag,
  faTasks,
  faThList,
  faBoltLightning,
  faTimes,
  faTrashAlt,
  faTrashCan,
  faTriangleExclamation,
  faUmbrella,
  faUser,
  faUserSlash,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWandMagicSparkles,
  faWrench,
];
