import {
  faArrowLeft, faAsterisk, faBan, faBars, faBell, faBolt, faBook, faCalendarAlt, faCheck, faCircle, faCircleCheck,
  faCircleHalfStroke, faCircleInfo, faClock, faCloud, faCogs, faComments, faCreditCard, faDatabase, faEnvelope,
  faEnvelopeCircleCheck, faEye, faFileImport, faFlag, faFloppyDisk, faHeart, faHome, faList, faLock, faLockOpen,
  faPencilAlt, faPhone, faPiggyBank, faPlus, faRepeat, faRoad, faSave, faSearch, faSheetPlastic, faSignInAlt,
  faSignOutAlt, faSlash, faSort, faSortDown, faSortUp, faSpinner, faStar, faSync, faTachometerAlt, faTag, faTasks,
  faThList, faTimes, faTrashAlt, faTrashCan, faTriangleExclamation, faUser, faUserPlus, faUsers, faUsersCog, faWrench,
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeIcons = [
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBolt,
  faBook,
  faCalendarAlt,
  faCheck,
  faCircle,
  faCircleCheck,
  faCircleInfo,
  faCircleHalfStroke,
  faClock,
  faCloud,
  faCogs,
  faComments,
  faCreditCard,
  faDatabase,
  faEnvelope,
  faEnvelopeCircleCheck,
  faEye,
  faFileImport,
  faFlag,
  faFloppyDisk,
  faHeart,
  faHome,
  faList,
  faLock,
  faLockOpen,
  faPencilAlt,
  faPhone,
  faPiggyBank,
  faPlus,
  faRepeat,
  faRoad,
  faSave,
  faSearch,
  faSheetPlastic,
  faSignOutAlt,
  faSignInAlt,
  faSlash,
  faSort,
  faSortDown,
  faSortUp,
  faSpinner,
  faStar,
  faSync,
  faTachometerAlt,
  faTag,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faTrashCan,
  faTriangleExclamation,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
];
